#
#  Copyright (c) 2018-2022 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devspaces-operator
  namespace: eclipse-che
  labels:
    app: devspaces-operator
    app.kubernetes.io/name: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: devspaces-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devspaces-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devspaces-operator
        app.kubernetes.io/name: che
        app.kubernetes.io/instance: che
        app.kubernetes.io/part-of: che.eclipse.org
        app.kubernetes.io/component: devspaces-operator
    spec:
      containers:
        - name: devspaces-operator
          image: quay.io/devspaces/devspaces-rhel8-operator:latest
          command:
            - /manager
          args:
            - --leader-elect
          imagePullPolicy: Always
          ports:
            - containerPort: 60000
              name: metrics
          env:
            - name: ADD_COMPONENT_READINESS_INIT_CONTAINERS
              value: 'false'
            - name: CHE_FLAVOR
              value: devspaces
            - name: CHE_VERSION
              value: 3.1.0
            - name: CONSOLE_LINK_DISPLAY_NAME
              value: Red Hat OpenShift Dev Spaces
            - name: CONSOLE_LINK_IMAGE
              value: /dashboard/assets/branding/loader.svg
            - name: CONSOLE_LINK_NAME
              value: che
            - name: CONSOLE_LINK_SECTION
              value: Red Hat Applications
            - name: MAX_CONCURRENT_RECONCILES
              value: '1'
            - name: OPERATOR_NAME
              value: devspaces-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_che_server
              value: quay.io/devspaces/server-rhel8:latest
            - name: RELATED_IMAGE_dashboard
              value: quay.io/devspaces/dashboard-rhel8:latest
            - name: RELATED_IMAGE_devfile_registry
              value: quay.io/devspaces/devfileregistry-rhel8:latest
            - name: RELATED_IMAGE_devworkspace_controller
              value: registry.redhat.io/devworkspace/devworkspace-rhel8-operator:0.13
            - name: RELATED_IMAGE_gateway_authentication_sidecar
              value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.8
            - name: RELATED_IMAGE_gateway_authorization_sidecar
              value: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.8
            - name: RELATED_IMAGE_internal_rest_backup_server
              value: quay.io/devspaces/backup-rhel8:latest
            - name: RELATED_IMAGE_plugin_registry
              value: quay.io/devspaces/pluginregistry-rhel8:latest
            - name: RELATED_IMAGE_postgres
              value: registry.redhat.io/rhel8/postgresql-96:1
            - name: RELATED_IMAGE_postgres_13_3
              value: registry.redhat.io/rhel8/postgresql-13:1
            - name: RELATED_IMAGE_pvc_jobs
              value: registry.redhat.io/ubi8/ubi-minimal:8.5
            - name: RELATED_IMAGE_single_host_gateway
              value: quay.io/devspaces/traefik-rhel8:latest
            - name: RELATED_IMAGE_single_host_gateway_config_sidecar
              value: quay.io/devspaces/configbump-rhel8:latest
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: Always
      serviceAccountName: devspaces-operator
      terminationGracePeriodSeconds: 20
