#
#  Copyright (c) 2018-2022 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
spec:
  server:
    cheFlavor: codeready
    cheClusterRoles: ''
    cheWorkspaceClusterRole: ''
    serverTrustStoreConfigMapName: ''
    gitSelfSignedCert: false
    tlsSupport: true
    proxyURL: ''
    proxyPort: ''
    proxyUser: ''
    proxyPassword: ''
    nonProxyHosts: ''
    workspaceNamespaceDefault: <username>-codeready
    allowUserDefinedWorkspaceNamespaces: false
    serverExposureStrategy: ''
    devfileRegistryImage: ''
    pluginRegistryImage: ''
  database:
    externalDb: false
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    chePostgresDb: ''
  storage:
    pvcStrategy: common
    pvcClaimSize: 10Gi
    preCreateSubPaths: true
    postgresPVCStorageClassName: ''
    workspacePVCStorageClassName: ''
  auth:
    initialOpenShiftOAuthUser: true
    externalIdentityProvider: false
    identityProviderURL: ''
    identityProviderAdminUserName: admin
    identityProviderPassword: admin
    identityProviderRealm: ''
    identityProviderClientId: ''
    oAuthClientName: ''
    oAuthSecret: ''
    identityProviderImage: ''
  metrics:
    enable: true
  devWorkspace:
    enable: false
