apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-che-operator
    app.kubernetes.io/part-of: devworkspace-che-operator
  name: devworkspace-che-manager
  namespace: devworkspace-che
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devworkspace-che-operator
      app.kubernetes.io/part-of: devworkspace-che-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devworkspace-che-operator
        app.kubernetes.io/part-of: devworkspace-che-operator
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /usr/local/bin/devworkspace-che-operator
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: devworkspace-operator
        - name: CONTROLLER_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: RELATED_IMAGE_gateway
          value: docker.io/traefik:v2.2.8
        - name: RELATED_IMAGE_gateway_configurer
          value: quay.io/che-incubator/configbump:0.1.4
        image: quay.io/che-incubator/devworkspace-che-operator:v7.28.2
        imagePullPolicy: Always
        name: devworkspace-che-operator
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: devworkspace-che-serviceaccount
      terminationGracePeriodSeconds: 10
