# This is an overlay that generates the "support" objects for the actual operator - the service account, roles, bindings, ...
namespace: devworkspace-che

namePrefix: devworkspace-che-

commonLabels:
  app.kubernetes.io/name: devworkspace-che-operator
  app.kubernetes.io/part-of: devworkspace-che-operator
  
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../components/rbac
