
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: chemanagers.che.eclipse.org
spec:
  group: che.eclipse.org
  names:
    kind: CheManager
    listKind: CheManagerList
    plural: chemanagers
    singular: chemanager
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CheManager is the configuration of the CheManager layer of Devworkspace.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CheManagerSpec holds the configuration of the Che controller.
            properties:
              gatewayConfigurerImage:
                description: GatewayConfigurerImage is the docker image to use for
                  the sidecar of the Che gateway that is used to configure it. This
                  is only used when GatewayDisabled is false. If not defined in the
                  CR, it is taken from the `RELATED_IMAGE_gateway_configurer` environment
                  variable of the che operator deployment/pod. If not defined there,
                  it defaults to a hardcoded value.
                type: string
              gatewayDisabled:
                description: "GatewayDisabled enables or disables routing of the url
                  rewrite supporting workspace endpoints through a common gateway
                  (the hostname of which is defined by the GatewayHost). \n Default
                  value is \"false\" meaning that the gateway is enabled. \n If set
                  to false (i.e. the gateway is enabled), endpoints marked using the
                  \"urlRewriteSupported\" attribute are exposed on unique subpaths
                  of the GatewayHost, while the rest of the workspace endpoints are
                  exposed on subdomains of the RoutingSuffix specified by the DevWorkspaceRouting
                  of the workspace. \n If set to true (i.e. the gateway is disabled),
                  all endpoints are deployed on subdomains of the RoutingSuffix."
                type: boolean
              gatewayHost:
                description: "GatewayHost is the full host name used to expose workspace
                  endpoints that support url rewriting reverse proxy. See the GatewayDisabled
                  attribute for a more detailed description of where and how are workspace
                  endpoints exposed in various configurations. \n This attribute is
                  mandatory on Kubernetes, optional on OpenShift."
                type: string
              gatewayImage:
                description: GatewayImage is the docker image to use for the Che gateway.  This
                  is only used if GatewayDisabled is false. If not defined in the
                  CR, it is taken from the `RELATED_IMAGE_gateway` environment variable
                  of the che operator deployment/pod. If not defined there, it defaults
                  to a hardcoded value.
                type: string
            type: object
          status:
            properties:
              gatewayHost:
                description: GatewayHost is the resolved host of the ingress/route,
                  on which the gateway is accessible.
                type: string
              gatewayPhase:
                description: GatewayPhase specifies the phase in which the singlehost
                  gateway deployment currently is. If the manager routing is not singlehost,
                  this is "Inactive"
                type: string
              message:
                description: Message contains further human-readable info for why
                  the manager is in the phase it currently is.
                type: string
              phase:
                description: Phase is the phase in which the manager as a whole finds
                  itself in.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
